{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "restaurant.fullname" (dict "root" . "name" "ingress") }}
  namespace: {{ include "restaurant.ns" . }}
  labels:
    {{- include "restaurant.labels" (dict "root" . "component" "ingress") | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    # 1) за статични файлове пазим пътя (/.+.<ext>)
    # 2) за всички останали пътища връщаме index.html (rewrite към /)
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ include "restaurant.ingress.hostFE" . }}
      http:
        paths:
          # статични ресурси: /static/*, /assets/*, файлове с разширение и т.н.
          - path: /()(?:static|assets)/?(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ include "restaurant.fullname" (dict "root" . "name" "frontend") }}
                port: { number: 80 }
          - path: /()(.*\..*)
            pathType: Prefix
            backend:
              service:
                name: {{ include "restaurant.fullname" (dict "root" . "name" "frontend") }}
                port: { number: 80 }
          # SPA fallback: всички пътища БЕЗ точка -> /
          - path: /(.+)
            pathType: Prefix
            backend:
              service:
                name: {{ include "restaurant.fullname" (dict "root" . "name" "frontend") }}
                port: { number: 80 }
          # коренът /
          - path: /()
            pathType: Prefix
            backend:
              service:
                name: {{ include "restaurant.fullname" (dict "root" . "name" "frontend") }}
                port: { number: 80 }

    - host: {{ include "restaurant.ingress.hostBE" . }}
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ include "restaurant.fullname" (dict "root" . "name" "backend") }}
                port: { number: 80 }
{{- end }}
