apiVersion: v1
kind: Secret
metadata:
  name: {{ include "restaurant.fullname" (dict "root" . "name" "app-env") }}
  namespace: {{ include "restaurant.ns" . }}
  labels:
    {{- include "restaurant.labels" (dict "root" . "component" "secrets") | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: "postgresql+psycopg://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@{{ include "restaurant.fullname" (dict "root" . "name" "postgres") }}:5432/{{ .Values.postgres.database }}"
  ADMIN_USERNAME: "{{ .Values.seed.adminUsername }}"
  ADMIN_PASSWORD: "{{ .Values.seed.adminPassword }}"
  SECRET_KEY: "{{ .Values.backend.secretKey }}"
